import {
  ChangeDetectionStrategy,
  Component,
  computed,
  inject,
  ViewEncapsulation
} from "@angular/core";
import { DesignSystemService } from "../../../services/design-system.service";

@Component({
  selector: "what-is",
  templateUrl: "./what-is.ng.html",
  styleUrl: "./what-is.scss",
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { class: "main-content" },
  encapsulation: ViewEncapsulation.None
})
export class WhatIsComponent {
  dsService = inject(DesignSystemService);

  ds = computed(() =>
    this.dsService.designSystem() === "mercury" ? "Mercury" : "Unanimo"
  );

  description = computed(() =>
    this.dsService.designSystem() === "mercury"
      ? "Mercury Design System is a robust and scalable solution designed to improve product development"
      : "Unanimo Design System is a solution oriented to mission-critical business applications and the back-office generated by GeneXus"
  );
}
