import { Component, computed, inject, ViewEncapsulation } from "@angular/core";
import { DesignSystemService } from "../../../services/design-system.service";

@Component({
  selector: "what-is",
  imports: [],
  templateUrl: "./what-is.component.html",
  host: { class: "main-content" },
  styleUrl: "./what-is.component.scss",
  encapsulation: ViewEncapsulation.None
})
export class WhatIsComponent {
  dsService = inject(DesignSystemService);

  ds = computed(() =>
    this.dsService.designSystem() === "mercury" ? "Mercury" : "Unanimo"
  );

  description = computed(() =>
    this.dsService.designSystem() === "mercury"
      ? "Mercury Design System is a robust and scalable solution designed to improve product development"
      : "Unanimo Design System is a solution oriented to mission-critical business applications and the back-office generated by GeneXus"
  );
}
