import { DOCUMENT, isPlatformBrowser } from "@angular/common";
import {
  inject,
  Injectable,
  PLATFORM_ID,
  Renderer2,
  RendererFactory2,
  signal
} from "@angular/core";

import { SEOService } from "./seo.service";
import { DesignSystem } from "../common/types";

const BASE_CSS_URL = "/assets/css/";
export const MERCURY_BASE_CSS_URL = `${BASE_CSS_URL}mercury/`;
export const UNANIMO_BASE_CSS_URL = `${BASE_CSS_URL}unanimo/`;
const DS_DATA_ATTRIBUTE = "data-design-system";

const getBaseBundle = (designSystem: DesignSystem) =>
  `${BASE_CSS_URL}${designSystem}/base/base.css` as const;

const getDSLink = () =>
  document.head.querySelector("[" + DS_DATA_ATTRIBUTE + "]") as HTMLLinkElement;

@Injectable({ providedIn: "root" })
export class DesignSystemService {
  private _document = inject(DOCUMENT);
  private platform = inject(PLATFORM_ID);
  private renderer2: Renderer2;
  private seoService = inject(SEOService);

  designSystem = signal<DesignSystem>("mercury");

  constructor(rendererFactory: RendererFactory2) {
    this.renderer2 = rendererFactory.createRenderer(null, null);
  }

  setDesignSystem(designSystem: DesignSystem) {
    this.designSystem.set(designSystem);

    // Browser. Update the link href with the new DS base bundle
    if (isPlatformBrowser(this.platform)) {
      const designSystemLink = getDSLink();
      designSystemLink.href = getBaseBundle(designSystem);
    }
    // Server. Create the link in the HTML with the DS base bundle
    else {
      const link = this.renderer2.createElement("link");
      link.rel = "stylesheet";
      link.href = getBaseBundle(designSystem);
      this.renderer2.setAttribute(link, DS_DATA_ATTRIBUTE, "");
      this.renderer2.appendChild(this._document.head, link);
    }

    this.seoService.updateDescription(
      designSystem === "mercury"
        ? "Mercury Design System is a robust and scalable solution designed to improve product development"
        : "Unanimo Design System is a solution oriented to mission-critical business applications and the back-office generated by GeneXus"
    );
  }
}
