import { DOCUMENT, isPlatformBrowser } from "@angular/common";
import {
  inject,
  Injectable,
  PLATFORM_ID,
  Renderer2,
  RendererFactory2
} from "@angular/core";
import { BehaviorSubject } from "rxjs/internal/BehaviorSubject";
import { SEOService } from "./seo.service";

@Injectable({ providedIn: "root" })
export class DesignSystemService {
  private _document = inject(DOCUMENT);
  private platform = inject(PLATFORM_ID);
  private renderer2: Renderer2;
  private seoService = inject(SEOService);

  private themeSubject = new BehaviorSubject<"mercury" | "unanimo">("mercury");

  theme$ = this.themeSubject.asObservable();

  constructor(rendererFactory: RendererFactory2) {
    this.renderer2 = rendererFactory.createRenderer(null, null);
  }

  setDesignSystem(designSystem: "mercury" | "unanimo") {
    this.themeSubject.next(designSystem);

    // Browser
    if (isPlatformBrowser(this.platform)) {
      const designSystemLink = document.head.querySelector(
        "[data-design-system]"
      ) as HTMLLinkElement;
      designSystemLink.href = `./assets/css/${designSystem}/all.css`;
    }
    // Server
    else {
      const link = this.renderer2.createElement("link");
      link.rel = "stylesheet";
      link.href = `./assets/css/${designSystem}/all.css`;
      this.renderer2.setAttribute(link, "data-design-system", "");
      this.renderer2.appendChild(this._document.head, link);
    }

    this.seoService.updateDescription(
      designSystem === "mercury"
        ? "Mercury Design System is a robust and scalable solution designed to improve product development"
        : "Unanimo Design System is a solution oriented to mission-critical business applications and the back-office generated by GeneXus"
    );
  }
}
