name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  install:
    uses: genexuslabs/design-systems/.github/workflows/install-and-deploy.yml@main
    with:
      node-version: "20.x"
      cache: true
      publish: false
      package: "packages/unanimo"
