# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package (dev)

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: "Name of the simulated tag" # Descripción del tag
        required: true                           # Obligatorio
        default: "v0.0.175"                      # Valor por defecto

jobs:
  check-version:
    runs-on: ubuntu-latest
    outputs:
      unanimo-changed: ${{ steps.check-unanimo.outputs.version-changed }}
      mercury-changed: ${{ steps.check-mercury.outputs.version-changed }}
      svg-sass-generator-changed: ${{ steps.check-svg-sass-generator.outputs.version-changed }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get latest published Unanimo version
        id: get-unanimo-version
        run: |
          PACKAGE_NAME=@genexus/unanimo
          LATEST_UNANIMO_VERSION=$(curl -s https://registry.npmjs.org/$PACKAGE_NAME | jq -r '.["dist-tags"].latest')
          echo "latest_unanimo_version=$LATEST_UNANIMO_VERSION" >> $GITHUB_ENV

      - name: Print tags
        run: |
          echo "The latest tag is ${{ env.latest_unanimo_version }}"
