name: Node.js Package

on:
  push:
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  publish-unanimo:
    uses: genexuslabs/design-systems/.github/workflows/install-and-deploy.yml@main
    with:
      node-version: "20.x"
      cache: false
      publish: true
      package: "packages/unanimo"
    secrets: inherit

  publish-mercury:
    uses: genexuslabs/design-systems/.github/workflows/install-and-deploy.yml@main
    with:
      node-version: "20.x"
      cache: false
      publish: true
      package: "packages/mercury"
    secrets: inherit

  publish-svg-sass-generator:
    uses: genexuslabs/design-systems/.github/workflows/install-and-deploy.yml@main
    with:
      node-version: "20.x"
      cache: false
      publish: true
      package: "packages/svg-sass-generator"
    secrets: inherit
