name: Node.js Package

on:
  push:
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  check-version:
    runs-on: ubuntu-latest
    outputs:
      unanimo-changed: ${{ steps.check-unanimo.outputs.version-changed }}
      mercury-changed: ${{ steps.check-mercury.outputs.version-changed }}
      svg-sass-generator-changed: ${{ steps.check-svg-sass-generator.outputs.version-changed }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get the latest Unanimo version
        id: get-latest-unanimo-version
        run: |
          PACKAGE_NAME=@genexus/unanimo
          LATEST_UNANIMO_VERSION=$(curl -s https://registry.npmjs.org/$PACKAGE_NAME | jq -r '.["dist-tags"].latest')
          echo "latest_unanimo_version=$LATEST_UNANIMO_VERSION" >> $GITHUB_ENV

      - name: Get the latest Mercury version
        id: get-latest-mercury-version
        run: |
          PACKAGE_NAME=@genexus/mercury
          LATEST_MERCURY_VERSION=$(curl -s https://registry.npmjs.org/$PACKAGE_NAME | jq -r '.["dist-tags"].latest')
          echo "latest_mercury_version=$LATEST_MERCURY_VERSION" >> $GITHUB_ENV

      - name: Get the latest SVG_Generator version
        id: get-latest-svg_generator-version
        run: |
          PACKAGE_NAME=@genexus/svg-sass-generator
          LATEST_SVG_GENERATOR_VERSION=$(curl -s https://registry.npmjs.org/$PACKAGE_NAME | jq -r '.["dist-tags"].latest')
          echo "latest_svg_generator_version=$LATEST_SVG_GENERATOR_VERSION" >> $GITHUB_ENV

      - name: Print last published versions
        run: |
          echo "The latest Unanimo version is ${{ env.latest_unanimo_version }}"
          echo "The latest Mercury version is ${{ env.latest_mercury_version }}"
          echo "The latest SVG Generator version is ${{ env.latest_svg_generator_version }}"

      - name: Check if `unanimo` version changed
        id: check-unanimo
        run: |
          CURRENT_VERSION=$(jq -r .version packages/unanimo/package.json)
          PREVIOUS_VERSION=${{ env.latest_unanimo_version }}
          if [ "$CURRENT_VERSION" != "$PREVIOUS_VERSION" ]; then
            echo "Version changed!"
            echo "version-changed=true" >> $GITHUB_OUTPUT
          else
            echo "version-changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Check if `mercury` version changed
        id: check-mercury
        run: |
          CURRENT_VERSION=$(jq -r .version packages/mercury/package.json)
          PREVIOUS_VERSION=${{ env.latest_mercury_version }}
          if [ "$CURRENT_VERSION" != "$PREVIOUS_VERSION" ]; then
            echo "Version changed!"
            echo "version-changed=true" >> $GITHUB_OUTPUT
          else
            echo "version-changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Check if `svg-sass-generator` version changed
        id: check-svg-sass-generator
        run: |
          CURRENT_VERSION=$(jq -r .version packages/svg-sass-generator/package.json)
          PREVIOUS_VERSION=${{ env.latest_svg_generator_version }}
          if [ "$CURRENT_VERSION" != "$PREVIOUS_VERSION" ]; then
            echo "Version changed!"
            echo "version-changed=true" >> $GITHUB_OUTPUT
          else
            echo "version-changed=false" >> $GITHUB_OUTPUT
          fi

  publish-unanimo:
    needs: check-version
    if: needs.check-version.outputs.unanimo-changed == 'true'
    uses: genexuslabs/design-systems/.github/workflows/install-and-deploy.yml@main
    with:
      node-version: "20.x"
      cache: false
      publish: true
      package: "packages/unanimo"
    secrets: inherit

  publish-mercury:
    needs: check-version
    if: needs.check-version.outputs.mercury-changed == 'true'
    uses: genexuslabs/design-systems/.github/workflows/install-and-deploy.yml@main
    with:
      node-version: "20.x"
      cache: false
      publish: true
      package: "packages/mercury"
    secrets: inherit

  publish-svg-sass-generator:
    needs: check-version
    if: needs.check-version.outputs.svg-sass-generator-changed == 'true'
    uses: genexuslabs/design-systems/.github/workflows/install-and-deploy.yml@main
    with:
      node-version: "20.x"
      cache: false
      publish: true
      package: "packages/svg-sass-generator"
    secrets: inherit
